# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kayıt_sayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3




class Ui_MainWindow_(object):

   

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 226)
        MainWindow.setStyleSheet("background-image: url(arka_plan/arkaplan.jpg);")
        MainWindow.setWindowIcon(QtGui.QIcon("arka_plan/sifre.jpg"))    
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 351, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")

        self.kullanici_adi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.verticalLayout.addWidget(self.kullanici_adi)

        self.sifre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sifre.setObjectName("sifre")
        self.verticalLayout.addWidget(self.sifre)
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)

        self.ad_soyad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ad_soyad.setObjectName("ad_soyad")
        self.verticalLayout.addWidget(self.ad_soyad)

        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.kayit)

        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# VERİ TABANİ OLUŞTURMA
        self.baglanti = sqlite3.connect("Veri_Tabani.sqlite")
        self.imlec = self.baglanti.cursor()
        self.imlec.execute("""CREATE TABLE IF NOT EXISTS k_bilgi
            (ID INTEGER PRIMARY KEY,
            _kullaniciadi STR(50),
            _sifre STR(50),
            _isimsoyad STR(50))""")
        self.baglanti.commit() 

    def kayit(self):
        #kadi = self.kullanici_adi.text()
        #sifre = self.sifre.text()
        #adsoyad = self.ad_soyad.text()
        #print(kadi,sifre)

        #self.imlec.execute("INSERT INTO k_bilgi VALUES(NULL,?,?,?)",(kadi,sifre,adsoyad))
        #self.baglanti.commit()


# 2. bir kayit oluşturmayı engelleyen bölüm
        while True:
            self.imlec.execute("SELECT ID FROM k_bilgi")
            ıd=self.imlec.fetchall()
            
            if ıd==[(1,)]:
                self.baglanti.close()
                msg = QMessageBox()
                msg.setWindowTitle('Sisteme Kayıtlısınız')
                msg.setText("Sisteme kayıtlısınız.")
                msg.setIcon(QMessageBox.Warning)
                msg.buttonClicked.connect(self.cikis)
                x= msg.exec_()
                break
#eksik bilgi girilmesini engeleyen bölüm            
            elif self.kullanici_adi.text()=='' or self.sifre.text()=='' or self.ad_soyad.text()=='' :
                msg = QMessageBox()
                msg.setWindowTitle('Boş Kutu')
                msg.setText('Bu Alanlar boş bırakılamaz.')
                msg.setIcon(QMessageBox.Warning)
                x= msg.exec_()
                break
#sisteme ilk defa kayıt yapmayı sağlayacak bölüm
            else:
                _kullaniciadi   =   self.kullanici_adi.text()
                _sifre          =   self.sifre.text()
                _isimsoyad      =   self.ad_soyad.text()  
        
                self.imlec.execute("INSERT INTO k_bilgi VALUES (NULL,?,?,?)",(_kullaniciadi,_sifre,_isimsoyad))   
                self.baglanti.commit()
            
                msg = QMessageBox()
                msg.setWindowTitle('Exit')
                msg.setText('Kaydınız tamamlandı uygulama kapanacak yeniden  açınız')
          
                msg.buttonClicked.connect(self.cikis)

                x= msg.exec_()
       

    def cikis(self,i):
        if i.text()=='OK':
            QtWidgets.qApp.quit()

    def retranslateUi(self, MainWindow):
    
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Güvenli Not kayıt"))
        self.kullanici_adi.setPlaceholderText(_translate("MainWindow", "Kullanıcı adınızı belirleyiniz"))
        self.sifre.setPlaceholderText(_translate("MainWindow", "Şifrenizi belirleyiniz"))
        self.ad_soyad.setPlaceholderText(_translate("MainWindow", "Ad soyad"))
        self.pushButton.setText(_translate("MainWindow", "Kaydet"))

