# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from sqlite3.dbapi2 import Cursor, connect
from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtGui import QIcon
from datetime import datetime
import time
from playsound import playsound
from PyQt5.QtWidgets import QMessageBox, QWidget
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
    
        
           

        self.connect = sqlite3.connect("notlar_veritabani.sqlite")
        self.cursor = self.connect.cursor()
        self.cursor.execute("""CREATE TABLE IF NOT EXISTS notlar(ID INTEGER PRIMARY KEY, _baslik_ TEXT,_not_ TEXT)""")
        self.connect.commit()
        #MainWindow.setStyleSheet("background-image: url(arka_plan/arkaplan.jpg);")
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon("arka_plan/notadd.jpg"))
        #MainWindow.setStyleSheet("background-image: url(arka_plan/res4.jpg);")
        MainWindow.resize(480, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 240, 461, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.kayit)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 490, 461, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.cagir)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 5, 461, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("background-color: rgb(220, 220, 220);"
        "border-radius: 5;border : 0px solid white;font-size: 10pt")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 461, 201))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("background-color: rgb(220, 220, 220);"
        "border-radius: 5;border : 0px solid white;font-size: 10pt")

        #self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        #self.lineEdit_3.setGeometry(QtCore.QRect(10, 280, 461, 201))
        #self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        #self.lineEdit_3.setObjectName("lineEdit_3")
        #self.lineEdit_3.setStyleSheet("color: rgb(5, 0, 0);"
        #"background-color: rgb(220, 220, 220);"
        #"border-radius: 5;border : 0px solid white;font-size: 10pt")


        self.gün=QtWidgets.QLineEdit(self.centralwidget)
        self.gün.setGeometry(QtCore.QRect(15, 530, 40, 31))
        self.gün.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gün.setObjectName("lineEdit_3")
        self.gün.setStyleSheet("background-color: rgb(220, 220, 220);"
        "border-radius: 5;border : 0px solid white;font-size: 10pt")


        self.saat=QtWidgets.QLineEdit(self.centralwidget)
        self.saat.setGeometry(QtCore.QRect(60, 530, 40, 31))
        self.saat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.saat.setObjectName("lineEdit_3")
        self.saat.setStyleSheet("background-color: rgb(220, 220, 220);"
        "border-radius: 5;border : 0px solid white;font-size: 10pt")


        self.dk=QtWidgets.QLineEdit(self.centralwidget)
        self.dk.setGeometry(QtCore.QRect(105, 530, 60, 31))
        self.dk.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dk.setObjectName("lineEdit_3")
        self.dk.setStyleSheet("background-color: rgb(220, 220, 220);"
        "border-radius: 5;border : 0px solid white;font-size: 10pt")
        
        #self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        #self.timeEdit.setGeometry(QtCore.QRect(10, 530, 151, 31))
        #self.timeEdit.setObjectName("timeEdit")

        self.alarm_kur = QtWidgets.QPushButton(self.centralwidget)
        self.alarm_kur.setEnabled(True)
        self.alarm_kur.setGeometry(QtCore.QRect(170, 530, 301, 31))
        self.alarm_kur.setObjectName("pushButton_3")
        self.alarm_kur.clicked.connect(self.alarm)

        self.not_sil = QtWidgets.QPushButton(self.centralwidget)
        self.not_sil.setEnabled(True)
        self.not_sil.setGeometry(QtCore.QRect(170, 563, 301, 31))
        self.not_sil.setObjectName("pushButton_3")
        self.not_sil.clicked.connect(self.sil)

        self.not_göster = QtWidgets.QTableWidget(self.centralwidget)
        self.not_göster.setGeometry(QtCore.QRect(10, 280, 461, 201))
        self.not_göster.setRowCount(10)
        self.not_göster.setColumnCount(3)
        self.not_göster.setHorizontalHeaderLabels(('ID','Başlık','Not'))

        self.lineEdit_= QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_.setGeometry(QtCore.QRect(10, 570, 150, 22))
        self.lineEdit_.setObjectName("lineEdit")


        #self.liste = QtWidgets.QListView(self.centralwidget)
        #self.liste.setGeometry(QtCore.QRect(90, 650, 300, 200))
        #self.liste.setObjectName("listView")

        #self.pushButton_3.clicked.connect(self.not_cagir)
        #self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_4.setEnabled(True)
        #self.pushButton_4.setGeometry(QtCore.QRect(170,570,301,31))
        #self.pushButton_4.setObjectName("pushButton_3")
# NOT ÇAĞIRMA 

        #self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        #self.comboBox.setGeometry(QtCore.QRect(10, 590, 151, 31))
        #self.comboBox.setObjectName("comboBox")

        #self.comboBox.addItem("1.Not")
        #self.comboBox.addItem("2.Not")
        #self.comboBox.addItem("3.Not")
        #self.comboBox.addItem("4.Not")
        #self.comboBox.addItem("5.Not")
        #self.comboBox.addItem("6.Not")
        #self.comboBox.addItem("7.Not")
        #self.comboBox.addItem("8.Not")
        #self.comboBox.addItem("9.Not")
        #self.comboBox.addItem("10.Not")

        #self.label = QtWidgets.QLabel(self.centralwidget)
        #self.label.setGeometry(QtCore.QRect(170, 570, 281, 21))
        #self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #liste = QtWidgets.QListView(self.centralwidget)
        #liste. setGeometry(QtCore.QRect(170, 500, 301, 31))
        #liste. setItemAlignment(QtCore.Qt.AlignCenter)
        
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
   
    def alarm(self):   
        
        saat = self.saat.text()
        dakika = self.dk.text()
        gün= self.gün.text()
        gün1 = int(gün)
        saat1 = int(saat)
        dakika1 =  int(dakika)
        
        
        while True:
            timenow = datetime.now()
            saat_al = timenow.hour
            gün = timenow.day
            dakika_al = timenow.minute
            
            print(timenow)

            if saat1 == saat_al and dakika1 == dakika_al and gün==gün1:
                print("Alarm Çaldi")
                playsound('Paydos.mp3')
                break
            else:
                time.sleep(1)
                continue

    def cagir(self):
        connection= sqlite3.connect("notlar_veritabani.sqlite")
        query="SELECT * FROM notlar"
        result=connection.execute(query)
        self.not_göster.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.not_göster.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.not_göster.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
        connection.close()
        self.cursor.execute("SELECT _baslik_ FROM notlar")

    def sil(self):

        index = self.lineEdit_.text()
        self.cursor.execute("DELETE  FROM notlar WHERE  ID= {} ".format(index)) 
        self.connect.commit()
        self.cagir()


    def kayit(self):
        
            _baslik_ = self.lineEdit.text()
            _not_ = self.lineEdit_2.text()

            self.cursor.execute("INSERT INTO notlar VALUES(NULL,?,?)",(_baslik_,_not_))
            self.connect.commit()
 
            msg = QMessageBox()
            msg.setWindowTitle('Kayıt Başarılı')
            msg.setText("Kayıt İşleminiz Başarılı Şekilde Gerçekleşti.")

            x= msg.exec_()
            self.cagir()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Not Ekle"))
        self.pushButton_2.setText(_translate("MainWindow", "Not Çağır"))
        self.saat.setPlaceholderText(_translate("MainWindow","Saat"))
        self.gün.setPlaceholderText(_translate("MainWindow","Gün"))
        self.dk.setPlaceholderText(_translate("MainWindow","Dakkika"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Başlık Giriniz"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Notunuzu Giriniz"))
        #self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Çağrılacak Not"))
        self.alarm_kur.setText(_translate("MainWindow", "Alarm Kur"))
        self.lineEdit_.setPlaceholderText(_translate("MainWindow","Id değerini giriniz"))
        self.not_sil.setText(_translate("MainWindow","Not Sil" ))
        #self.pushButton_4.setText(_translate("MainWindow", "Not Çağır"))
        #self.label.setText(_translate("MainWindow", "Alarm Kurmak İstediğiniz Notu Seçiniz"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

